apiVersion: v2
name: jira-service-desk-operator
description: Helm Chart for jira-service-desk-operator

type: application

sources:
  - https://github.com/stakater/jira-service-desk-operator

# Helm chart Version
version:  0.0.33

# Application version to be deployed
appVersion:  0.0.33

keywords:
  - stakater
  - sro
  - jira-service-desk-operator
  - jira
  - service desk

# Maintainers
maintainers:
  - name: stakater
    email: hello@stakater.com

icon: https://github.com/stakater/ForecastleIcons/blob/master/stakater.png
